### ISSUE TITLE
Which station data we will use?

### ISSUE THREAD

**Issue by AhmedCode99** [ubsuny/23-Homework5G5#1]

**Comment by sharmistharanit** [comment]
We are not sure yet. However, most likely we picked up data station 12 (Bermuda one). @AhmedCode99

**Comment by LinxuanHu** [comment]
we G3 choose Ascension Island, United Kingdom (ASC)

**Comment by AhmedCode99** [comment]
G5 Chose: Cape Kumukahi, Hawaii, United States (KUM)
