### ISSUE TITLE
Confusion about task 1

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework5G5#12]
Hello group 5,
I am confused ,how to start with task 1. t says to write a function that calculates the frequency in useful unit. Should we read the data and write function to calculate frequency.  Any overview regarding the task  1 is highly appreciated

**Comment by reshnashrestha** [comment]
Same here. I just so confused that I am not able to start and on top of that there are a lot to be done except for this hw.

**Comment by pratibha77118** [comment]
@reshnashrestha Do you have any idea for now?

**Comment by AhmedCode99** [comment]
any ideas

**Comment by AhmedCode99** [comment]
We wrote a function. Check out fft.py on our main repo.
