### ISSUE TITLE
Station chosen!

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework5G5#13]
We, G1, are planning to choose "Sand Island, Midway, United States (MID)" station. What about you guys?

**Comment by LinxuanHu** [comment]
we G3 choose Ascension Island, United Kingdom (ASC)

**Comment by tirthbha** [comment]
@LinxuanHu What about frequency? I mean, have you assigned the appropriate unit for the frequency?

**Comment by AhmedCode99** [comment]
Nice

**Comment by AhmedCode99** [comment]
we chose KUM
