### ISSUE TITLE
Task 1 file format

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework5G5#19]
Is the file format for task 1 should be in py or ipynb?

**Comment by Mosaddeq107** [comment]
> Is the file format for task 1 should be in py or ipynb?

In another issue, Dr. Tim replied and suggested using py.

**Comment by reshnashrestha** [comment]
or, we can keep the ipynb and then create library in py for different functions that way it will be more efficient.

**Comment by AhmedCode99** [comment]
both work
