### ISSUE TITLE
Members of G5

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework5G5#20]
Who are the members of group 5?

**Comment by Mosaddeq107** [comment]
Hi, I couldn't find any member of this group in the contributor section. What is happening in this group?

**Comment by sharmistharanit** [comment]
No response yet.

**Comment by reshnashrestha** [comment]
Yes I’m curious

**Comment by AhmedCode99** [comment]
I can't speak for jimmy, but I have given up. I hope that satisfied your curiosity :)

**Comment by AhmedCode99** [comment]
Sad
