### ISSUE TITLE
data

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework5G5#21]
Which data are you using? Thank you

**Comment by Mosaddeq107** [comment]
Hi, @uarif,
Which dataset you're using in your work?

**Comment by reshnashrestha** [comment]
@Mosaddeq107 we are using Sand Island MID

**Comment by uarif** [comment]
I myself, used the same data Dr. Tim used in the class, I don't remember the station name. @Mosaddeq107

**Comment by AhmedCode99** [comment]
KUM Station
