### ISSUE TITLE
Data Selectioin

### ISSUE THREAD

**Issue by Mosaddeq107** [ubsuny/23-Homework5G5#24]
Hi, all of G5, did you select the dataset for your task?

**Comment by reshnashrestha** [comment]
Same question, there is no update in this group.

**Comment by sharmistharanit** [comment]
Yes, I think you guys need to start.

**Comment by reshnashrestha** [comment]
May be they are working on forked repo

**Comment by AhmedCode99** [comment]
nothing yet

**Comment by AhmedCode99** [comment]
Cape Kumukahi, Hawaii, United States (KUM) is our data
