### ISSUE TITLE
Inverse fft

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework5G5#26]
Are we supposed to perform inverse fft on the original X or the filtered X?

**Comment by sharmistharanit** [comment]
I am not sure about that. Any suggestion will be appreciated.

**Comment by AhmedCode99** [comment]
I dont think we need inverse fft for task 1

**Comment by s4il3sh** [comment]
> I dont think we need inverse fft for task 1

He is talking about task 2.

**Comment by AhmedCode99** [comment]
We are not doing task2, so we cant hep you out
