### ISSUE TITLE
Function for actual frequency?

### ISSUE THREAD

**Issue by sharmistharanit** [ubsuny/23-Homework5G5#27]
Has anyone figured out the function for actual frequency?

**Comment by reshnashrestha** [comment]
Actual frequency?

**Comment by AhmedCode99** [comment]
what do you mean

**Comment by reshnashrestha** [comment]
@sharmistharanit can you explain your question

**Comment by AhmedCode99** [comment]
We wrote a function. Check out fft.py on our main repo.
