### ISSUE TITLE
task 1 issue

### ISSUE THREAD

**Issue by s4il3sh** [ubsuny/23-Homework5G5#28]
how did you guys find the frequency is it after fft?

**Comment by sharmistharanit** [comment]
Group 4 has done some work. You can have a look.

**Comment by AhmedCode99** [comment]
I have an idea, we can invert the data and use numpy.min()

**Comment by s4il3sh** [comment]
> I have an idea, we can invert the data and use numpy.min()

What's the difference without inverting it and using np.max()?

**Comment by s4il3sh** [comment]
> Group 4 has done some work. You can have a look.

Thank you  but does your code works? What frequency you guys got it from the code?

**Comment by AhmedCode99** [comment]
We wrote a function. Look at it in our repo. File name fft.py
