### ISSUE TITLE
Station Chosen: Cape Kumukahi, Hawaii, United States (KUM)

### ISSUE THREAD

**Issue by AhmedCode99** [ubsuny/23-Homework5G5#34]
Here is a link to the data:
https://gml.noaa.gov/aftp/data/trace_gases/co2/flask/surface/txt/co2_kum_surface-flask_1_ccgg_month.txt

**Comment by AhmedCode99** [comment]
@WildJimmy Please notice

**Comment by WildJimmy** [comment]
Noticed 👍
