### ISSUE TITLE
What are the units for amplitude of FT?

### ISSUE THREAD

**Issue by AhmedCode99** [ubsuny/23-Homework5G5#38]
Before the FT, we had the concentration of CO2 in ppm, after the Fourier transform is it reasonable to talk about units?

I think we just call the y-axis, intensity in a.u.

**Comment by s4il3sh** [comment]
isn't it power? if it is log you are plotting then it has no units.

**Comment by AhmedCode99** [comment]
The units of Fourier transform is the same as that of the original data. But you are write log is dimensionless.
