### ISSUE TITLE
Do we need sampling frequency to calculate the frequency in "in useful units"?

### ISSUE THREAD

**Issue by AhmedCode99** [ubsuny/23-Homework5G5#39]
I think that a reasonable way to find the frequency is by using the sampling frequency. 

I don't think that the website lists that, so is it safe to assume that it is 1 sample per month?

**Comment by s4il3sh** [comment]
I have seen some guys are using sampling frequency in their to calculate frequency. What is the purpose of using sampling frequency? Can't we simply develop a code that counts the peaks?

**Comment by WildJimmy** [comment]
I think sampling frequency is necessary to determine the actual time, but I'm not sure where to fund it

**Comment by WildJimmy** [comment]
The sampling frequency is monthly, as if you examine the data you can see that there is one data point per month
