### ISSUE TITLE
Question confusion

### ISSUE THREAD

**Issue by sharmistharanit** [ubsuny/23-Homework5G5#6]
What are we supposed to do to address the task (Write a function that calculates the actual frequency in useful units)? Any help will be appreciated.

**Comment by Mosaddeq107** [comment]
Did you get your answer? If so, can you please explain it to me?

**Comment by AhmedCode99** [comment]
Tell me if you figured it out

**Comment by AhmedCode99** [comment]
We wrote a function. Check out fft.py on our main repo.
