### ISSUE TITLE
Proper frequency unit

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework5G5#7]
What could be the proper frequency unit?

**Comment by pratibha77118** [comment]
I too am confused what exactly is proper frequency unit to be taken?

**Comment by reshnashrestha** [comment]
If you got any lead please let me know

**Comment by Mosaddeq107** [comment]
Someone used cycles per month (cycles/month) for the frequency unit.

**Comment by AhmedCode99** [comment]
Good idea, any more guesses?

**Comment by reshnashrestha** [comment]
What about your guess?

**Comment by AhmedCode99** [comment]
1/Time
