### ISSUE TITLE
Task 1 discussion 

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework5G5#8]
Who is doing task 1 in this group?

**Comment by reshnashrestha** [comment]
Hi group 5 have you worked on any? Because I want to discuss on task 1. There are several confusion.

**Comment by AhmedCode99** [comment]
I am doing 1, why are you confused

**Comment by reshnashrestha** [comment]
The one to calculate peak frequency and the proper unit.
Can you share your insights?

**Comment by AhmedCode99** [comment]
We wrote a function. Check out fft.py on our main repo.
