### ISSUE TITLE
New pull request confusion #g5

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework5G5#9]
Hi guys, I see that there is a new PR in your group by someone and I don’t think he is in our class or if I am mistaken can you please check and explain this. 
https://github.com/ubsuny/23-Homework5G5/pulls

**Comment by reshnashrestha** [comment]
@laserlab @WildJimmy @AhmedCode99 
Do you happen to know him? Or is that the GitHub name of you two?

**Comment by laserlab** [comment]
Why don't you guys interact with the person on the pull request and just ask. At the end it is a public repository and everybody can do pull requests

**Comment by reshnashrestha** [comment]
Yeah sure, Will do that.
